#!/bin/bash

if pgrep xcompmgr &>/dev/null; then
    pkill -f xcompmgr
fi

xcompmgr -cC &

if pgrep trayer &>/dev/null; then
    pkill -f trayer
fi

trayer --edge bottom --align right --SetDockType true --SetPartialStrut true \
 --expand true --width 5 --transparent true --alpha 0 --tint 0x283339 --height 17 &

feh --bg-scale "/home/itsuwari/wallpapers/youmu.jpg"

nm-applet &

xset r rate 300 50
