#!/bin/bash

if pgrep xcompmgr &>/dev/null; then
    pkill -f xcompmgr
fi

xcompmgr -c &

if pgrep trayer &>/dev/null; then
    pkill -f trayer
fi

trayer --edge top --align right --SetDockType true --SetPartialStrut true \
 --expand true --width 10 --transparent true --tint 0x5f5f5f --height 18 &

feh --bg-scale "/home/itsuwari/wallpapers/youmu.jpg"

nm-applet &

xset r rate 300 50
